### ISSUE TITLE
name for the project

### ISSUE THREAD

**Issue by ltalirz** [jan-janssen/comp-mat-sci-llm#7]
Our agent should have a name - let's collect one name per comment and use thumbs up to vote

**Comment by ltalirz** [comment]
AtomIQ

(already taken by some supply chain company)

**Comment by ltalirz** [comment]
MatAMA

**Comment by pagel-s** [comment]
MaterAilize

**Comment by btrungvo** [comment]
Materio

**Comment by chiang-yuan** [comment]
LangSim

**Comment by pablo-unzueta** [comment]
StructuraAI

**Comment by utkarshp1161** [comment]
MatChainSim

**Comment by Bernadette-Mohr** [comment]
> Materio

MaterIO ?

**Comment by btrungvo** [comment]
> > Materio
> 
> MaterIO ?

Yes that looks better.

**Comment by jan-janssen** [comment]
We decided on LangSim
